// Code generated by protoc-gen-go.
// source: relay.proto
// DO NOT EDIT!

/*
Package relay is a generated protocol buffer package.

It is generated from these files:
	relay.proto

It has these top-level messages:
	RelayMessage
	JoinMessage
	LeaveMessage
	ChannelIncomingMessage
	ChannelOutgoingMessage
*/
package relay

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type RelayMessage struct {
	Join  *JoinMessage            `protobuf:"bytes,10,opt,name=join" json:"join,omitempty"`
	Leave *LeaveMessage           `protobuf:"bytes,11,opt,name=leave" json:"leave,omitempty"`
	Msg   *ChannelIncomingMessage `protobuf:"bytes,12,opt,name=msg" json:"msg,omitempty"`
}

func (m *RelayMessage) Reset()                    { *m = RelayMessage{} }
func (m *RelayMessage) String() string            { return proto.CompactTextString(m) }
func (*RelayMessage) ProtoMessage()               {}
func (*RelayMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *RelayMessage) GetJoin() *JoinMessage {
	if m != nil {
		return m.Join
	}
	return nil
}

func (m *RelayMessage) GetLeave() *LeaveMessage {
	if m != nil {
		return m.Leave
	}
	return nil
}

func (m *RelayMessage) GetMsg() *ChannelIncomingMessage {
	if m != nil {
		return m.Msg
	}
	return nil
}

type JoinMessage struct {
	Channel string `protobuf:"bytes,1,opt,name=channel" json:"channel,omitempty"`
}

func (m *JoinMessage) Reset()                    { *m = JoinMessage{} }
func (m *JoinMessage) String() string            { return proto.CompactTextString(m) }
func (*JoinMessage) ProtoMessage()               {}
func (*JoinMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *JoinMessage) GetChannel() string {
	if m != nil {
		return m.Channel
	}
	return ""
}

type LeaveMessage struct {
	Channel string `protobuf:"bytes,1,opt,name=channel" json:"channel,omitempty"`
}

func (m *LeaveMessage) Reset()                    { *m = LeaveMessage{} }
func (m *LeaveMessage) String() string            { return proto.CompactTextString(m) }
func (*LeaveMessage) ProtoMessage()               {}
func (*LeaveMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *LeaveMessage) GetChannel() string {
	if m != nil {
		return m.Channel
	}
	return ""
}

type ChannelIncomingMessage struct {
	Channel string `protobuf:"bytes,1,opt,name=channel" json:"channel,omitempty"`
	Blob    []byte `protobuf:"bytes,2,opt,name=blob,proto3" json:"blob,omitempty"`
}

func (m *ChannelIncomingMessage) Reset()                    { *m = ChannelIncomingMessage{} }
func (m *ChannelIncomingMessage) String() string            { return proto.CompactTextString(m) }
func (*ChannelIncomingMessage) ProtoMessage()               {}
func (*ChannelIncomingMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *ChannelIncomingMessage) GetChannel() string {
	if m != nil {
		return m.Channel
	}
	return ""
}

func (m *ChannelIncomingMessage) GetBlob() []byte {
	if m != nil {
		return m.Blob
	}
	return nil
}

type ChannelOutgoingMessage struct {
	Channel string `protobuf:"bytes,1,opt,name=channel" json:"channel,omitempty"`
	Address string `protobuf:"bytes,2,opt,name=address" json:"address,omitempty"`
	Blob    []byte `protobuf:"bytes,3,opt,name=blob,proto3" json:"blob,omitempty"`
}

func (m *ChannelOutgoingMessage) Reset()                    { *m = ChannelOutgoingMessage{} }
func (m *ChannelOutgoingMessage) String() string            { return proto.CompactTextString(m) }
func (*ChannelOutgoingMessage) ProtoMessage()               {}
func (*ChannelOutgoingMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *ChannelOutgoingMessage) GetChannel() string {
	if m != nil {
		return m.Channel
	}
	return ""
}

func (m *ChannelOutgoingMessage) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *ChannelOutgoingMessage) GetBlob() []byte {
	if m != nil {
		return m.Blob
	}
	return nil
}

func init() {
	proto.RegisterType((*RelayMessage)(nil), "RelayMessage")
	proto.RegisterType((*JoinMessage)(nil), "JoinMessage")
	proto.RegisterType((*LeaveMessage)(nil), "LeaveMessage")
	proto.RegisterType((*ChannelIncomingMessage)(nil), "ChannelIncomingMessage")
	proto.RegisterType((*ChannelOutgoingMessage)(nil), "ChannelOutgoingMessage")
}

func init() { proto.RegisterFile("relay.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 222 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x8c, 0x91, 0xb1, 0x4e, 0xc5, 0x20,
	0x18, 0x85, 0x83, 0xf7, 0xea, 0x4d, 0x7f, 0x70, 0x61, 0x50, 0x46, 0x82, 0x83, 0xb8, 0x30, 0xe8,
	0x23, 0x98, 0x98, 0x68, 0x34, 0x26, 0x3c, 0x81, 0xb4, 0x25, 0x58, 0x43, 0xc1, 0x94, 0x6a, 0xe2,
	0xe6, 0xa3, 0x9b, 0x52, 0xa9, 0x1d, 0xd4, 0xdc, 0x8d, 0x93, 0xf3, 0x71, 0xbe, 0xe1, 0x07, 0x3c,
	0x58, 0x6f, 0x3e, 0xd4, 0xeb, 0x10, 0xc7, 0x28, 0x3e, 0x11, 0x10, 0x3d, 0xe5, 0x07, 0x9b, 0x92,
	0x71, 0x96, 0x72, 0xd8, 0xbe, 0xc4, 0x2e, 0x30, 0xe0, 0x48, 0xe2, 0x4b, 0xa2, 0xee, 0x62, 0x17,
	0xbe, 0x3b, 0x9d, 0x1b, 0x7a, 0x06, 0x87, 0xde, 0x9a, 0x77, 0xcb, 0x70, 0x46, 0x8e, 0xd5, 0xfd,
	0x94, 0x0a, 0x33, 0x77, 0xf4, 0x02, 0x36, 0x7d, 0x72, 0x8c, 0x64, 0xe4, 0x54, 0x5d, 0x3f, 0x9b,
	0x10, 0xac, 0xbf, 0x0d, 0x4d, 0xec, 0xbb, 0xe0, 0x0a, 0x3c, 0x31, 0xe2, 0x1c, 0xf0, 0x4a, 0x42,
	0x19, 0xec, 0x9a, 0x99, 0x66, 0x88, 0x23, 0x59, 0xe9, 0x12, 0x85, 0x04, 0xb2, 0x56, 0xfd, 0x43,
	0xde, 0xc0, 0xc9, 0xef, 0xc6, 0xbf, 0xff, 0x50, 0x0a, 0xdb, 0xda, 0xc7, 0x9a, 0x1d, 0x70, 0x24,
	0x89, 0xce, 0x6f, 0xf1, 0xb4, 0xec, 0x3c, 0xbe, 0x8d, 0x2e, 0xee, 0xb5, 0xc3, 0x60, 0x67, 0xda,
	0x76, 0xb0, 0x29, 0xe5, 0xa9, 0x4a, 0x97, 0xb8, 0x18, 0x36, 0x3f, 0x86, 0xfa, 0x28, 0x9f, 0xe1,
	0xea, 0x2b, 0x00, 0x00, 0xff, 0xff, 0xe4, 0x0c, 0x6a, 0xec, 0x95, 0x01, 0x00, 0x00,
}
